### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by dimusiq** [javascripteverywhere/api#20]
Hello, i have problems with commad "npm install" after that there's lots of errors and i can't run the project.  Like it seems that many modules got updated in past few years and API is simply outdated and don't mach current version of Apollo server for example.

**Comment by hillonyechekwa** [comment]
I tried installing the latest version of every dependency listed in the package.json but I still got some errors.

` npm install                                                              
 npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: notedly-api@1.0.0
npm ERR! Found: graphql@16.2.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"latest" from the root project
npm ERR!   peer graphql@"^15.3.0 || ^16.0.0" from apollo-server-express@3.6.1
npm ERR!   node_modules/apollo-server-express
npm ERR!     apollo-server-express@"latest" from the root project
npm ERR!   1 more (graphql-depth-limit)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! graphql-iso-date@"latest" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: graphql@14.7.0
npm ERR! node_modules/graphql
npm ERR!   peer graphql@"^0.5.0 || ^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0" from graphql-iso-date@3.6.1
npm ERR!   node_modules/graphql-iso-date
npm ERR!     graphql-iso-date@"latest" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Hill\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Hill\AppData\Local\npm-cache\_logs\2022-01-15T19_09_49_421Z-debug.log`

**Comment by RobSchilderr** [comment]
> I tried installing the latest version of every dependency listed in the package.json but I still got some errors.
> 
> ` npm install npm ERR! code ERESOLVE npm ERR! ERESOLVE could not resolve npm ERR! npm ERR! While resolving: notedly-api@1.0.0 npm ERR! Found: graphql@16.2.0 npm ERR! node_modules/graphql npm ERR! graphql@"latest" from the root project npm ERR! peer graphql@"^15.3.0 || ^16.0.0" from apollo-server-express@3.6.1 npm ERR! node_modules/apollo-server-express npm ERR! apollo-server-express@"latest" from the root project npm ERR! 1 more (graphql-depth-limit) npm ERR! npm ERR! Could not resolve dependency: npm ERR! graphql-iso-date@"latest" from the root project npm ERR! npm ERR! Conflicting peer dependency: graphql@14.7.0 npm ERR! node_modules/graphql npm ERR! peer graphql@"^0.5.0 || ^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0" from graphql-iso-date@3.6.1 npm ERR! node_modules/graphql-iso-date npm ERR! graphql-iso-date@"latest" from the root project npm ERR! npm ERR! Fix the upstream dependency conflict, or retry npm ERR! this command with --force, or --legacy-peer-deps npm ERR! to accept an incorrect (and potentially broken) dependency resolution. npm ERR! npm ERR! See C:\Users\Hill\AppData\Local\npm-cache\eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\Hill\AppData\Local\npm-cache_logs\2022-01-15T19_09_49_421Z-debug.log`

Did you fix this in the end?
